version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./dockerfiles/dev/go_api/Dockerfile
    image: golang:1.20
    volumes:
      - ./go_api:/go/src/app
    tty: true
    ports:
      - 8080:8080

  postgres:
    image: postgres:15
    volumes:
      - ./go_api/ent/migrate/migrations/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_db
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
