version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile.dev
    volumes:
      - ./web:/app
      - node_modules:/app/node_modules
    tty: true
    ports:
      - 3000:3000
    environment:
      REACT_APP_REST_URL: "http://localhost:8080"

  api:
    build:
      context: .
      dockerfile: ./go_api/Dockerfile.dev
    volumes:
      - ./go_api:/go/src/app
    tty: true
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_db
      ALLOWORIGINS: "http://localhost:3000"
      DEV: true

  postgres:
    image: postgres:14
    volumes:
      - ./go_api/ent/migrate/migrations/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_db
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432

volumes:
  node_modules:
