// Code generated by ent, DO NOT EDIT.

package ent

import (
	"HDYS-TTBYS/my-todo/ent/schema"
	"HDYS-TTBYS/my-todo/ent/todo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescIsComplete is the schema descriptor for is_complete field.
	todoDescIsComplete := todoFields[3].Descriptor()
	// todo.DefaultIsComplete holds the default value on creation for the is_complete field.
	todo.DefaultIsComplete = todoDescIsComplete.Default.(bool)
}
