apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: default
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: ${DOCKERHUB_USERNAME}/my-todo-go-api:${GITHUB_SHA}
          env:
            - name: POSTGRES_HOST
              valueFrom:
                { secretKeyRef: { name: todo-db-pguser-todo-db, key: host } }
            - name: POSTGRES_PORT
              valueFrom:
                { secretKeyRef: { name: todo-db-pguser-todo-db, key: port } }
            - name: POSTGRES_DB
              valueFrom:
                { secretKeyRef: { name: todo-db-pguser-todo-db, key: dbname } }
            - name: POSTGRES_USER
              valueFrom:
                { secretKeyRef: { name: todo-db-pguser-todo-db, key: user } }
            - name: POSTGRES_PASSWORD
              valueFrom:
                {
                  secretKeyRef: { name: todo-db-pguser-todo-db, key: password },
                }
          name: api
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
