apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tthd-app
spec:
  secretName: tthd-app-tls-wc
  commonName: "*.tthd-app.link" # ワイルドカード証明書
  dnsNames:
    - "*.tthd-app.link"
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
