apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: tatehide151@outlook.jp
    server: https://acme-staging-v02.api.letsencrypt.org/directory # staging
    # server: https://acme-v02.api.letsencrypt.org/directory # prod
    privateKeySecretRef:
      name: tthd-app-isser-account-key
    solvers:
      - selector:
          dnsZones:
            - "tthd-app.link"
        dns01:
          route53:
            region: ap-northeast-1
            accessKeyID: ${ACCESSKEYID}
            secretAccessKeySecretRef:
              name: prod-route53-credentials-secret
              key: secret-access-key
