FROM golang:1.20

WORKDIR /go/src/app

ADD ./ .

RUN apt update
RUN apt install -y sqlite3

RUN go install entgo.io/ent/cmd/ent@latest
RUN go install github.com/golang/mock/mockgen@v1.6.0

EXPOSE 8080
