/* tslint:disable */
/* eslint-disable */
/**
 * my-todo-api
 * テスト用todo
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tatehide151@outlook.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ToDo } from './ToDo';
import {
    ToDoFromJSON,
    ToDoFromJSONTyped,
    ToDoToJSON,
} from './ToDo';

/**
 * 
 * @export
 * @interface GetTodos200Response
 */
export interface GetTodos200Response {
    /**
     * 
     * @type {number}
     * @memberof GetTodos200Response
     */
    total: number;
    /**
     * 
     * @type {Array<ToDo>}
     * @memberof GetTodos200Response
     */
    todos?: Array<ToDo>;
}

/**
 * Check if a given object implements the GetTodos200Response interface.
 */
export function instanceOfGetTodos200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function GetTodos200ResponseFromJSON(json: any): GetTodos200Response {
    return GetTodos200ResponseFromJSONTyped(json, false);
}

export function GetTodos200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTodos200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': json['total'],
        'todos': !exists(json, 'todos') ? undefined : ((json['todos'] as Array<any>).map(ToDoFromJSON)),
    };
}

export function GetTodos200ResponseToJSON(value?: GetTodos200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'todos': value.todos === undefined ? undefined : ((value.todos as Array<any>).map(ToDoToJSON)),
    };
}

