/* tslint:disable */
/* eslint-disable */
/**
 * my-todo-api
 * テスト用todo
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tatehide151@outlook.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTodoRequest
 */
export interface PostTodoRequest {
    /**
     * Todoのタイトル
     * @type {string}
     * @memberof PostTodoRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PostTodoRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTodoRequest
     */
    assiginPerson: string;
}

/**
 * Check if a given object implements the PostTodoRequest interface.
 */
export function instanceOfPostTodoRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "assiginPerson" in value;

    return isInstance;
}

export function PostTodoRequestFromJSON(json: any): PostTodoRequest {
    return PostTodoRequestFromJSONTyped(json, false);
}

export function PostTodoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTodoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'assiginPerson': json['assigin_person'],
    };
}

export function PostTodoRequestToJSON(value?: PostTodoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'assigin_person': value.assiginPerson,
    };
}

