/* tslint:disable */
/* eslint-disable */
/**
 * my-todo-api
 * テスト用todo
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tatehide151@outlook.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Todoオブジェクトの共通スキーマ
 * @export
 * @interface ToDo
 */
export interface ToDo {
    /**
     * ユニークID
     * @type {number}
     * @memberof ToDo
     */
    readonly id: number;
    /**
     * Todoのタイトル
     * @type {string}
     * @memberof ToDo
     */
    title: string;
    /**
     * Todoの説明
     * @type {string}
     * @memberof ToDo
     */
    description?: string;
    /**
     * Todoの完了・未完了を示すフラグ（trueが完了）
     * @type {boolean}
     * @memberof ToDo
     */
    isComplete?: boolean;
    /**
     * Todoを担当する人の名前
     * @type {string}
     * @memberof ToDo
     */
    assaginPerson?: string | null;
    /**
     * Todoが作成された時刻（UNIXタイムで単位は秒）
     * @type {number}
     * @memberof ToDo
     */
    readonly createdAt: number;
    /**
     * Todoが更新された時刻（UNIXタイムで単位は秒）
     * @type {number}
     * @memberof ToDo
     */
    readonly updatedAt?: number;
}

/**
 * Check if a given object implements the ToDo interface.
 */
export function instanceOfToDo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function ToDoFromJSON(json: any): ToDo {
    return ToDoFromJSONTyped(json, false);
}

export function ToDoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToDo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'isComplete': !exists(json, 'is_complete') ? undefined : json['is_complete'],
        'assaginPerson': !exists(json, 'assagin_person') ? undefined : json['assagin_person'],
        'createdAt': json['created_at'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
    };
}

export function ToDoToJSON(value?: ToDo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'is_complete': value.isComplete,
        'assagin_person': value.assaginPerson,
    };
}

