/* tslint:disable */
/* eslint-disable */
/**
 * my-todo-api
 * テスト用todo
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tatehide151@outlook.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTodoIdRequest
 */
export interface UpdateTodoIdRequest {
    /**
     * Todoのタイトル
     * @type {string}
     * @memberof UpdateTodoIdRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoIdRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoIdRequest
     */
    assiginPerson: string;
    /**
     * Todoの完了・未完了を示すフラグ（trueが完了）
     * @type {boolean}
     * @memberof UpdateTodoIdRequest
     */
    isComplete: boolean;
}

/**
 * Check if a given object implements the UpdateTodoIdRequest interface.
 */
export function instanceOfUpdateTodoIdRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "assiginPerson" in value;
    isInstance = isInstance && "isComplete" in value;

    return isInstance;
}

export function UpdateTodoIdRequestFromJSON(json: any): UpdateTodoIdRequest {
    return UpdateTodoIdRequestFromJSONTyped(json, false);
}

export function UpdateTodoIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTodoIdRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'assiginPerson': json['assigin_person'],
        'isComplete': json['is_complete'],
    };
}

export function UpdateTodoIdRequestToJSON(value?: UpdateTodoIdRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'assigin_person': value.assiginPerson,
        'is_complete': value.isComplete,
    };
}

