-- Create "todos" table
CREATE TABLE "todos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "assagin_person" character varying NOT NULL, "created_at" timestamptz NOT NULL, "description" character varying NOT NULL, "is_complete" boolean NOT NULL DEFAULT false, "title" character varying NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
