name: Api CI
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "go_api/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Test
        run: |
          go test -v ./...
        working-directory: go_api
        env:
          GOPATH: /home/runner/work/woodpecker/go
