name: EntCI
on:
  push:
    # Run whenever code is changed in the master.
    branches:
      - main
  # Run on PRs where something changed under the `ent/` directory.
  pull_request:
    paths:
      - "go_api/ent/*"
jobs:
  ent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: ent/contrib/ci@master
